server:
  port: 8080 

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-seguridad
          uri: lb://MS-SEGURIDAD
          predicates:
            - Path=/api/auth/**

        - id: ms-usuarios
          uri: lb://MS-USUARIOS
          predicates:
            - Path=/api/usuarios/**

        - id: ms-catalogo
          uri: lb://MS-CATALOGO
          predicates:
            - Path=/api/catalogo/**

        - id: ms-promociones
          uri: lb://MS-PROMOCIONES
          predicates:
            - Path=/api/promociones/**
        
        - id: ms-pedidos
          uri: lb://MS-PEDIDOS
          predicates:
            - Path=/api/pedidos/**
        
        - id: eureka-server
          uri: lb://EUREKA-SERVER
          predicates:
            - Path=/api/eureka/**
        
        - id: ms-inventario
          uri: lb://MS-INVENTARIO
          predicates:
            - Path=/api/inventario/**
        
        - id: ms-logistica
          uri: lb://MS-LOGISTICA
          predicates:
            - Path=/api/logistica/**
        
        - id: ms-notificaciones
          uri: lb://MS-NOTIFICACIONES
          predicates:
            - Path=/api/notificaciones/**

        - id: ms-pagos
          uri: lb://MS-PAGOS
          predicates:
            - Path=/api/pagos/**
        
        - id: ms-reportes
          uri: lb://MS-REPORTES
          predicates:
            - Path=/api/reportes/**

        - id: ms-seguimiento
          uri: lb://MS-SEGUIMIENTO
          predicates:
            - Path=/api/seguimiento/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true